In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("data/dataset_conversaciones/dataset_50k_anonymized.csv")
df

,input,output,date,conv_id,user_id,channel_source
0,"Me enteré de una promo ""Supercashback Pagos Gu...",Claro que puedo ayudarte! Para participar en l...,2025-08-17,000502c2-288c-41f6-b751-a8b45a376a81,USR-09092,1
1,La tarjeta de crédito Hey Negocios es diferent...,Claro! La Tarjeta de Crédito Hey Negocios es d...,2025-08-17,000502c2-288c-41f6-b751-a8b45a376a81,USR-09092,1
2,"Entiendo, gracias",¡De nada! Me alegra haber podido ayudarte. Si ...,2025-08-17,000502c2-288c-41f6-b751-a8b45a376a81,USR-09092,1
3,Hola,¡Hola! ¿Cómo estás? Estoy aquí para ayudarte c...,2025-09-16,00221607-cdb2-47f2-a9ac-913d4c7744c6,USR-09344,1
4,Verificación de cuenta,Claro que puedo ayudarte con eso. Para validar...,2025-09-16,00221607-cdb2-47f2-a9ac-913d4c7744c6,USR-09344,1
...,...,...,...,...,...,...
49994,Cómo puedo verificar tarjeta para usar en Appl...,Claro que puedo ayudarte con eso. Para verific...,2025-10-25,221B2A02-FA14-451B-916A-5DE70CCC3679,USR-04904,1
49995,Hola no puedo hacer un retiro sin Tarjeta y,Lamento escuchar eso. Para hacer un retiro sin...,2025-09-30,5769ccdd-6bd3-48bf-9953-6fd4c4e5f1a1,USR-11158,1
49996,Hice una queja y me pide una contraseña provic...,Claro que puedo ayudarte. Para seguir el progr...,2025-08-23,f742315f-5064-4467-a3da-d3476e2f3c28,USR-13210,1
49997,No me deja transferir porque me dice que el to...,Lamento escuchar eso. Si estás teniendo proble...,2025-10-18,8543484E-49DA-4341-B1F6-08FEC214E6A3,USR-02245,1
49998,como le hago para verificar mi tarjeta para ap...,Claro que puedo ayudarte! Para verificar tu ta...,2025-10-17,217DE74A-E49A-48AA-A948-9CA50AE59132,USR-07334,1

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 49999 entries, 0 to 49998
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   input           49976 non-null  str
 1   output          49999 non-null  str
 2   date            49999 non-null  str
 3   conv_id         49999 non-null  str
 4   user_id         49999 non-null  str
 5   channel_source  49999 non-null  int64
dtypes: int64(1), str(5)
memory usage: 2.3 MB

In [4]:
df.isnull().sum()

input             23
output             0
date               0
conv_id            0
user_id            0
channel_source     0
dtype: int64

In [5]:
dfn = df[df['input'].isnull()]
dfn

,input,output,date,conv_id,user_id,channel_source
1415,NaN,¡Hola! Parece que no has escrito tu pregunta. ...,2025-08-09,0d0a62cd7dd1134100a4a3842b2792a9,USR-01347,1
5833,NaN,Claro que puedo ayudarte. El nombre del endoso...,2025-10-13,2c088c59b62230ca6d1035256a3f8a2a,USR-12356,1
5834,NaN,"¡Hola! Veo que tienes una pregunta, ¿en qué pu...",2025-10-13,2c088c59b62230ca6d1035256a3f8a2a,USR-12356,1
5836,NaN,"Claro que sí, te explico. En el caso de tu cré...",2025-10-13,2c088c59b62230ca6d1035256a3f8a2a,USR-12356,1
5838,NaN,"Claro que sí, te puedo ayudar con eso. El nomb...",2025-10-13,2c088c59b62230ca6d1035256a3f8a2a,USR-12356,1
5839,NaN,"Claro que sí, con gusto te ayudo. El nombre de...",2025-10-13,2c088c59b62230ca6d1035256a3f8a2a,USR-12356,1
7136,NaN,"Claro que sí, puedes transferir el saldo de ot...",2025-08-26,360CF3E7-4521-4AF2-AA4C-D05F173D70FD,USR-02997,1
14326,NaN,¡De nada! Si en algún momento tienes más pregu...,2025-08-07,6bec96d0abf1dd3d6f73ef59643bd1c1,USR-05487,1
19302,NaN,¡Hola! ¿En qué puedo ayudarte hoy? Si tienes a...,2025-10-19,8e1629f692e55ba0ee14113fdc4af3ce,USR-11760,1
28172,NaN,"¡Hola! Veo que tienes una pregunta, ¿en qué pu...",2025-08-19,a59da9b3383ad1847561bd698619d4a8,USR-12942,1
28176,NaN,"Claro, perfecto. Me alegra que vayas a intenta...",2025-08-19,a59da9b3383ad1847561bd698619d4a8,USR-12942,1
28177,NaN,"¡Hola! Veo que tu mensaje está en blanco, ¿en ...",2025-08-19,a59da9b3383ad1847561bd698619d4a8,USR-12942,1
28178,NaN,"Claro que sí, me parece una excelente idea que...",2025-08-19,a59da9b3383ad1847561bd698619d4a8,USR-12942,1
28180,NaN,Si en la llamada no reconocen tu número de cli...,2025-08-19,a59da9b3383ad1847561bd698619d4a8,USR-12942,1
28182,NaN,Lamento que estés teniendo ese problema. Si no...,2025-08-20,a59da9b3383ad1847561bd698619d4a8,USR-12942,1
29200,NaN,¡Hola! ¿En qué puedo ayudarte hoy? Si tienes a...,2025-09-27,b1d6ca79278498758a3ef8adab9390bc,USR-10382,1
30864,NaN,Claro! La Tarjeta de Crédito Tradicional Hey t...,2025-10-09,cba8fee7385b8759c6d1c9cc7ce34de1,USR-01565,1
30865,NaN,¡Hola! Veo que tienes una Cuenta Hey y una Tar...,2025-10-09,cba8fee7385b8759c6d1c9cc7ce34de1,USR-01565,1
30866,NaN,Claro que puedo ayudarte con gusto. Veo que ti...,2025-10-09,cba8fee7385b8759c6d1c9cc7ce34de1,USR-01565,1
31048,NaN,"No, no es necesario que hables con un asesor p...",2025-08-11,cd8c6d6520d36492c0dffe29bed90e92,USR-04177,1
31050,NaN,¡Hola! Parece que no has escrito tu pregunta. ...,2025-08-11,cd8c6d6520d36492c0dffe29bed90e92,USR-04177,1
31051,NaN,¡Claro! Estoy aquí para ayudarte. Si tienes al...,2025-08-11,cd8c6d6520d36492c0dffe29bed90e92,USR-04177,1
32039,NaN,¡Hola! Parece que no has escrito tu pregunta. ...,2025-09-07,d8a2a44e88b52057fbd73cec38b64a88,USR-02805,1

In [6]:
df = df[df['input'].notnull()]
df

,input,output,date,conv_id,user_id,channel_source
0,"Me enteré de una promo ""Supercashback Pagos Gu...",Claro que puedo ayudarte! Para participar en l...,2025-08-17,000502c2-288c-41f6-b751-a8b45a376a81,USR-09092,1
1,La tarjeta de crédito Hey Negocios es diferent...,Claro! La Tarjeta de Crédito Hey Negocios es d...,2025-08-17,000502c2-288c-41f6-b751-a8b45a376a81,USR-09092,1
2,"Entiendo, gracias",¡De nada! Me alegra haber podido ayudarte. Si ...,2025-08-17,000502c2-288c-41f6-b751-a8b45a376a81,USR-09092,1
3,Hola,¡Hola! ¿Cómo estás? Estoy aquí para ayudarte c...,2025-09-16,00221607-cdb2-47f2-a9ac-913d4c7744c6,USR-09344,1
4,Verificación de cuenta,Claro que puedo ayudarte con eso. Para validar...,2025-09-16,00221607-cdb2-47f2-a9ac-913d4c7744c6,USR-09344,1
...,...,...,...,...,...,...
49994,Cómo puedo verificar tarjeta para usar en Appl...,Claro que puedo ayudarte con eso. Para verific...,2025-10-25,221B2A02-FA14-451B-916A-5DE70CCC3679,USR-04904,1
49995,Hola no puedo hacer un retiro sin Tarjeta y,Lamento escuchar eso. Para hacer un retiro sin...,2025-09-30,5769ccdd-6bd3-48bf-9953-6fd4c4e5f1a1,USR-11158,1
49996,Hice una queja y me pide una contraseña provic...,Claro que puedo ayudarte. Para seguir el progr...,2025-08-23,f742315f-5064-4467-a3da-d3476e2f3c28,USR-13210,1
49997,No me deja transferir porque me dice que el to...,Lamento escuchar eso. Si estás teniendo proble...,2025-10-18,8543484E-49DA-4341-B1F6-08FEC214E6A3,USR-02245,1
49998,como le hago para verificar mi tarjeta para ap...,Claro que puedo ayudarte! Para verificar tu ta...,2025-10-17,217DE74A-E49A-48AA-A948-9CA50AE59132,USR-07334,1

In [10]:
df.isnull().sum()

input             0
output            0
date              0
conv_id           0
user_id           0
channel_source    0
dtype: int64